import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const books = [
  // Classic (7)
  { title: "The Great Gatsby", author: "F. Scott Fitzgerald", description: "A story of the mysteriously wealthy Jay Gatsby and his love for Daisy Buchanan, set in the Jazz Age.", price: 12.99, genre: "Classic", rating: 4.5, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg", fullDescription: "The Great Gatsby, F. Scott Fitzgerald's third book, stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted 'ichstocking turned to bootlegging,' has been described as a cautionary tale regarding the American Dream.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Great_Gatsby" },
  { title: "To Kill a Mockingbird", author: "Harper Lee", description: "A gripping tale of racial injustice and childhood innocence in the American South during the 1930s.", price: 14.99, genre: "Classic", rating: 4.8, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg", fullDescription: "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. 'To Kill a Mockingbird' became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film. Compassionate, dramatic, and deeply moving, it takes readers to the roots of human behavior — to innocence and experience, kindness and cruelty, love and hatred, humor and pathos.", wikipediaUrl: "https://en.wikipedia.org/wiki/To_Kill_a_Mockingbird" },
  { title: "The Catcher in the Rye", author: "J.D. Salinger", description: "The story of Holden Caulfield's experiences in New York City after being expelled from prep school.", price: 11.49, genre: "Classic", rating: 4.1, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg", fullDescription: "Since his debut in 1951 as The Catcher in the Rye, Holden Caulfield has been synonymous with 'cynical adolescent.' Holden narrates the story of a couple of days in his sixteen-year-old life, just after he's been expelled from prep school. With his style of narration, Holden exposes the phoniness of the adult world while confessing his own confusion and disillusionment.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Catcher_in_the_Rye" },
  { title: "Jane Eyre", author: "Charlotte Brontë", description: "An orphaned young woman becomes governess at Thornfield Hall and falls in love with the mysterious Mr. Rochester.", price: 10.99, genre: "Classic", rating: 4.5, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg", fullDescription: "Orphaned as a child, Jane has felt an outsider her whole young life. Her courage is tested once more when she arrives at Thornfield Hall, where she has been hired as governess. Jane's employer, the brooding Mr. Rochester, draws her in with a passion she has never before experienced. But dark secrets lurk within Thornfield, and Jane's principled nature will be challenged in ways she never imagined.", wikipediaUrl: "https://en.wikipedia.org/wiki/Jane_Eyre" },
  { title: "Wuthering Heights", author: "Emily Brontë", description: "A tale of passionate and destructive love between Heathcliff and Catherine on the Yorkshire moors.", price: 11.49, genre: "Classic", rating: 4.3, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780141439556-L.jpg", fullDescription: "Lockwood, the new tenant of Thrushcross Grange, discovers the history of the Earnshaw and Linton families through the housekeeper Nelly Dean. At the heart of the story is the passionate and destructive love between Catherine Earnshaw and the orphan Heathcliff. The intensity of their bond, set against the harsh Yorkshire moors, leads to obsession, revenge, and tragedy that spans two generations.", wikipediaUrl: "https://en.wikipedia.org/wiki/Wuthering_Heights" },
  { title: "Great Expectations", author: "Charles Dickens", description: "The coming-of-age story of Pip, an orphan who dreams of becoming a gentleman in Victorian England.", price: 10.49, genre: "Classic", rating: 4.4, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780141439563-L.jpg", fullDescription: "In what may be Dickens's best novel, humble, orphaned Pip is apprenticed to the dirty work of the forge but dares to dream of becoming a gentleman. When an anonymous benefactor makes Pip's dream a reality, he discovers that wealth and privilege come at a heavy price. A gripping tale of crime and guilt, revenge and reward, that captures both the cruelty and the comedy of the Victorian age.", wikipediaUrl: "https://en.wikipedia.org/wiki/Great_Expectations" },
  { title: "Moby-Dick", author: "Herman Melville", description: "Captain Ahab's obsessive quest to hunt the white whale that crippled him on a previous voyage.", price: 13.99, genre: "Classic", rating: 4.2, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780142437247-L.jpg", fullDescription: "On a previous voyage, a mysterious white whale had torn off Captain Ahab's leg. Now the captain of the Pequod, Ahab is consumed with hunting down Moby Dick. Ishmael, a young seaman, narrates their doomed quest across the vast oceans. Rich with symbolism and philosophical depth, Moby-Dick is at once an adventure story, an examination of obsession, and a meditation on the nature of evil.", wikipediaUrl: "https://en.wikipedia.org/wiki/Moby-Dick" },
  // Dystopian (5)
  { title: "1984", author: "George Orwell", description: "A dystopian novel set in a totalitarian society ruled by Big Brother, exploring themes of surveillance and control.", price: 11.99, genre: "Dystopian", rating: 4.7, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg", fullDescription: "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its dystopian purgatory becomes more real. Published in 1949, the book offers a vision of a totalitarian future where one party controls every aspect of citizens' lives. Winston Smith, a man in grave danger simply for thinking, works at the Ministry of Truth, where his job is to rewrite history. The society he lives in is watched over by Big Brother, and independent thinking is a crime.", wikipediaUrl: "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four" },
  { title: "Brave New World", author: "Aldous Huxley", description: "A futuristic society where humans are engineered and conditioned for a seemingly perfect existence.", price: 13.49, genre: "Dystopian", rating: 4.4, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg", fullDescription: "Aldous Huxley's profoundly important classic of world literature, Brave New World is a searching vision of an unequal, technologically-advanced future where humans are genetically bred, socially indoctrinated, and pharmaceutically anesthetized to passively uphold an authoritarian ruling order — all at the cost of our freedom, full humanity, and perhaps our souls.", wikipediaUrl: "https://en.wikipedia.org/wiki/Brave_New_World" },
  { title: "Fahrenheit 451", author: "Ray Bradbury", description: "In a future where books are banned, a fireman begins to question his role in burning them.", price: 11.99, genre: "Dystopian", rating: 4.5, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg", fullDescription: "Guy Montag is a fireman. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden. Montag never questions the destruction and ruin his actions produce, returning each day to his bland life and wife, Mildred. But when he meets Clarisse, a young woman who tells him of a past when people were not afraid, Montag begins to question everything.", wikipediaUrl: "https://en.wikipedia.org/wiki/Fahrenheit_451" },
  { title: "The Handmaid's Tale", author: "Margaret Atwood", description: "In the theocratic Republic of Gilead, women are stripped of their rights and forced into servitude.", price: 14.99, genre: "Dystopian", rating: 4.4, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780385490818-L.jpg", fullDescription: "Offred is a Handmaid in the Republic of Gilead. She may leave the Commander's home only on shopping trips, and once a month she must submit to a ceremony in hopes of conception. But Offred remembers a time before, when she lived and made choices, had a job, a family, a name. Now, in this new world order, she has none of that — except the power of her own mind and the seeds of rebellion.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Handmaid%27s_Tale" },
  { title: "The Giver", author: "Lois Lowry", description: "In a seemingly perfect community without pain or suffering, a boy discovers the dark truth behind his society.", price: 9.99, genre: "Dystopian", rating: 4.3, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780544336261-L.jpg", fullDescription: "Jonas's world is perfect. Everything is under control. There is no war or fear or pain. There are no choices. Every person is assigned a role in the Community. When Jonas turns twelve, he is singled out to receive special training from The Giver. The Giver alone holds the memories of the true pain and pleasure of life. Now it is time for Jonas to receive the truth.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Giver" },
  // Fantasy (6)
  { title: "The Hobbit", author: "J.R.R. Tolkien", description: "Bilbo Baggins embarks on an unexpected journey with a company of dwarves to reclaim their homeland.", price: 15.99, genre: "Fantasy", rating: 4.7, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg", fullDescription: "In a hole in the ground there lived a hobbit. So begins one of the most beloved and delightful tales in the English language — Tolkien's prelude to The Lord of the Rings. Bilbo Baggins, a respectable, well-to-do hobbit, is tricked by Gandalf the wizard into sharing in an adventure with thirteen dwarves. They set off on a quest to raid the treasure hoard guarded by Smaug the Magnificent, a large and very dangerous dragon.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Hobbit" },
  { title: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", description: "An orphaned boy discovers he is a wizard and begins his education at Hogwarts School of Witchcraft and Wizardry.", price: 12.99, genre: "Fantasy", rating: 4.8, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780590353427-L.jpg", fullDescription: "Harry Potter has never been the star of a Quidditch team or won a house cup. He knows no spells, has never helped to hatch a dragon, and has certainly never worn a cloak of invisibility. All he knows is a miserable life with the Dursleys. That is, until a mysterious letter arrives by owl messenger: a letter with an invitation to an incredible place that Harry — and anyone who reads about him — will find unforgettable.", wikipediaUrl: "https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone" },
  { title: "A Game of Thrones", author: "George R.R. Martin", description: "Noble families vie for control of the Iron Throne while an ancient enemy returns after centuries of sleep.", price: 16.99, genre: "Fantasy", rating: 4.6, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780553573404-L.jpg", fullDescription: "Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister and supernatural forces are massing beyond the kingdom's protective Wall. At the center of the conflict lie the Starks of Winterfell, a family as combative and stubborn as the harsh land they were born to.", wikipediaUrl: "https://en.wikipedia.org/wiki/A_Game_of_Thrones" },
  { title: "The Name of the Wind", author: "Patrick Rothfuss", description: "Kvothe recounts his transformation from a young outcast to the most notorious wizard of his time.", price: 15.49, genre: "Fantasy", rating: 4.6, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780756404741-L.jpg", fullDescription: "Told in Kvothe's own voice, this is the tale of the magically gifted young man who grows to be the most notorious wizard his world has ever seen. From his childhood in a troupe of traveling players, to years spent as a near-feral orphan, to his time as a student at a legendary school of magic, this is a story of transformation — as a young man discovers his extraordinary nature and battles a terrible enemy.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Name_of_the_Wind" },
  { title: "The Lion, the Witch and the Wardrobe", author: "C.S. Lewis", description: "Four siblings discover a magical land through a wardrobe and help free it from eternal winter.", price: 10.99, genre: "Fantasy", rating: 4.5, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780064404990-L.jpg", fullDescription: "Four adventurous siblings — Peter, Susan, Edmund, and Lucy Pevensie — step through a wardrobe door and into the land of Narnia, a land frozen in eternal winter and enslaved by the power of the White Witch. Under the guidance of the great lion Aslan, and with the help of many wonderful creatures, the children lead Narnia into a glorious spring and a new era of peace and prosperity.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Lion,_the_Witch_and_the_Wardrobe" },
  { title: "Mistborn: The Final Empire", author: "Brandon Sanderson", description: "In a world of ash and darkness, a street thief discovers she has extraordinary powers and joins a rebellion.", price: 14.99, genre: "Fantasy", rating: 4.7, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780765311788-L.jpg", fullDescription: "For a thousand years the ash fell and no flowers bloomed. For a thousand years the Skaa slaved in misery and lived in fear. For a thousand years the Lord Ruler reigned with absolute power and ultimate terror. Then Kelsier snapped. A half-Skaa, half-nobleman, he recruited the underworld's elite to teach them Allomancy — the mystical art of burning metals — and orchestrate an audacious plot to overthrow the Final Empire.", wikipediaUrl: "https://en.wikipedia.org/wiki/Mistborn:_The_Final_Empire" },
  // Science Fiction (6)
  { title: "Dune", author: "Frank Herbert", description: "An epic saga of politics, religion, and ecology on the desert planet Arrakis.", price: 16.99, genre: "Science Fiction", rating: 4.6, inStock: false, coverImage: "https://covers.openlibrary.org/b/isbn/9780441013593-L.jpg", fullDescription: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is 'the spice' melange — a drug capable of extending life and expanding consciousness. When his family is betrayed, Paul must journey into the desert to find the Fremen, and to fulfill his destiny as the Kwisatz Haderach, the prophesied leader who will change the course of the universe.", wikipediaUrl: "https://en.wikipedia.org/wiki/Dune_(novel)" },
  { title: "Ender's Game", author: "Orson Scott Card", description: "A brilliant child is trained in a military academy in space to prepare for an alien invasion.", price: 13.99, genre: "Science Fiction", rating: 4.6, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780812550702-L.jpg", fullDescription: "Andrew 'Ender' Wiggin thinks he is playing computer simulated war games; he is, in fact, engaged in something far more desperate. Ender may be the military genius Earth desperately needs in a war against an inscrutable alien enemy. The only way to find out is to throw him into ever harsher training, to chip away at his isolation, and to discover if he has the ability to save the world.", wikipediaUrl: "https://en.wikipedia.org/wiki/Ender%27s_Game" },
  { title: "The Hitchhiker's Guide to the Galaxy", author: "Douglas Adams", description: "Arthur Dent is swept off Earth moments before its destruction and begins an absurd journey through space.", price: 11.99, genre: "Science Fiction", rating: 4.5, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg", fullDescription: "Seconds before Earth is demolished to make way for a galactic freeway, Arthur Dent is plucked off the planet by his friend Ford Prefect, a researcher for the revised edition of The Hitchhiker's Guide to the Galaxy. Together they begin a journey through space aided by quotes from the Guide ('A towel is about the most massively useful thing an interstellar hitchhiker can have') and a galaxy-full of fellow travelers.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Hitchhiker%27s_Guide_to_the_Galaxy_(novel)" },
  { title: "Foundation", author: "Isaac Asimov", description: "A mathematician develops a science to predict the future and establishes a foundation to preserve knowledge.", price: 14.49, genre: "Science Fiction", rating: 4.4, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg", fullDescription: "For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. Only Hari Seldon, creator of the revolutionary science of psychohistory, can see into the future — a dark age of ignorance, barbarism, and warfare that will last thirty thousand years. To preserve knowledge and save humankind, Seldon gathers the best minds in the Empire and settles them on a bleak planet at the edge of the galaxy.", wikipediaUrl: "https://en.wikipedia.org/wiki/Foundation_(Asimov_novel)" },
  { title: "Neuromancer", author: "William Gibson", description: "A washed-up computer hacker is hired for one last job: a heist against a powerful artificial intelligence.", price: 13.49, genre: "Science Fiction", rating: 4.2, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780441569595-L.jpg", fullDescription: "Case was the sharpest data-thief in the matrix — until he crossed the wrong people. Burned out and suicidal, he's living on the streets of Chiba City, Japan. Then a shadowy conspiracy offers him a second chance — and a cure — in exchange for his skills in cyberspace. The stakes are higher than anything he's ever faced as Case plunges into the digital realm on a mission against a powerful artificial intelligence.", wikipediaUrl: "https://en.wikipedia.org/wiki/Neuromancer" },
  { title: "The Martian", author: "Andy Weir", description: "An astronaut stranded on Mars must use his ingenuity and wit to survive and signal Earth for rescue.", price: 14.99, genre: "Science Fiction", rating: 4.6, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780553418026-L.jpg", fullDescription: "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there. After a dust storm forces his crew to evacuate and leave him behind, Mark finds himself stranded and completely alone with no way to signal Earth. Drawing on his training and resourcefulness, he must find a way to survive on a hostile planet with only limited supplies.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Martian_(novel)" },
  // Romance (5)
  { title: "Pride and Prejudice", author: "Jane Austen", description: "A witty romance about Elizabeth Bennet and Mr. Darcy navigating society, class, and their own pride.", price: 10.99, genre: "Romance", rating: 4.6, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg", fullDescription: "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. The story follows the main character, Elizabeth Bennet, as she deals with issues of manners, upbringing, morality, education, and marriage in the society of the landed gentry of the British Regency. Elizabeth is the second of five daughters of a country gentleman living near the fictional town of Meryton.", wikipediaUrl: "https://en.wikipedia.org/wiki/Pride_and_Prejudice" },
  { title: "Outlander", author: "Diana Gabaldon", description: "A World War II nurse is swept back in time to 18th-century Scotland where she meets a Highland warrior.", price: 15.99, genre: "Romance", rating: 4.5, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780440212560-L.jpg", fullDescription: "The year is 1945. Claire Randall, a former combat nurse, has just returned from the war and is reunited with her husband on a second honeymoon. Walking through a stone circle in the Scottish Highlands, she is suddenly transported to 1743 — and plunged into the intrigues of clans and the Jacobite risings. Forced to marry Jamie Fraser, a chivalrous young Scottish warrior, she becomes torn between two lives and two men.", wikipediaUrl: "https://en.wikipedia.org/wiki/Outlander_(novel)" },
  { title: "The Notebook", author: "Nicholas Sparks", description: "A love story told through an elderly man reading to a woman suffering from dementia in a nursing home.", price: 11.99, genre: "Romance", rating: 4.2, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780446676090-L.jpg", fullDescription: "Every so often a love story so captures our hearts that it becomes more than a story — it becomes part of how we see the world. Set amid the austere beauty of coastal North Carolina in 1946, The Notebook begins with the story of Noah Calhoun, a rural Southerner recently returned from war. Noah is restoring a plantation home when Allie Nelson, the girl he once loved, suddenly reappears in his life.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Notebook" },
  { title: "Me Before You", author: "Jojo Moyes", description: "A young woman becomes caretaker for a paralyzed man and they develop an unexpected bond that changes both their lives.", price: 12.99, genre: "Romance", rating: 4.3, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780143124542-L.jpg", fullDescription: "Lou Clark knows lots of things. She knows how many footsteps there are between the bus stop and home. She knows she likes working in The Buttered Bun tea shop and she knows she might not love her boyfriend Patrick. What Lou doesn't know is she's about to lose her job, or that knowing what's coming is what keeps her sane. Will Traynor knows his motorcycle accident took away his desire to live. Lou is about to change everything.", wikipediaUrl: "https://en.wikipedia.org/wiki/Me_Before_You" },
  { title: "The Time Traveler's Wife", author: "Audrey Niffenegger", description: "A love story about a man with a genetic disorder that causes him to time travel unpredictably.", price: 13.49, genre: "Romance", rating: 4.1, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9781476764832-L.jpg", fullDescription: "This extraordinary, magical novel is the story of Clare and Henry, who have known each other since Clare was six and Henry was thirty-six, and were married when Clare was twenty-two and Henry thirty. Deeply in love, they must cope with Henry's Chrono-Displacement Disorder, which causes him to travel through time involuntarily, arriving naked and without resources at random moments.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Time_Traveler%27s_Wife" },
  // Mystery (6)
  { title: "The Girl with the Dragon Tattoo", author: "Stieg Larsson", description: "A journalist and a young computer hacker investigate a wealthy family's dark secrets.", price: 14.99, genre: "Mystery", rating: 4.4, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780307454546-L.jpg", fullDescription: "Harriet Vanger, a scion of one of Sweden's wealthiest families, disappeared over forty years ago. All these years later, her aged uncle continues to seek the truth. He hires Mikael Blomkvist, a crusading journalist, and Lisbeth Salander, a tattooed, pierced, computer hacker with a troubled past, to investigate. They discover a trail of dark family secrets spanning decades of hatred, corruption, and murder.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Girl_with_the_Dragon_Tattoo" },
  { title: "Gone Girl", author: "Gillian Flynn", description: "On the morning of their fifth anniversary, a woman disappears and suspicion falls on her husband.", price: 13.99, genre: "Mystery", rating: 4.3, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg", fullDescription: "On a warm summer morning in North Carthage, Missouri, Nick and Amy Dunne celebrate their fifth wedding anniversary. Presents are being wrapped and reservations are being made when Nick's clever and beautiful wife disappears. Under mounting pressure from the police and a media frenzy, Nick's portrait of a blissful union begins to crumble. What are the lies, and what is the truth?", wikipediaUrl: "https://en.wikipedia.org/wiki/Gone_Girl_(novel)" },
  { title: "The Da Vinci Code", author: "Dan Brown", description: "A symbologist and a cryptologist follow clues hidden in Leonardo da Vinci's works to uncover a secret.", price: 14.49, genre: "Mystery", rating: 4.0, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg", fullDescription: "While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered, and a baffling cipher has been found near the body. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Da_Vinci_Code" },
  { title: "And Then There Were None", author: "Agatha Christie", description: "Ten strangers are lured to an island and begin to die one by one according to a nursery rhyme.", price: 10.99, genre: "Mystery", rating: 4.6, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780062073488-L.jpg", fullDescription: "Ten strangers are lured to an isolated island mansion off the Devon coast by a mysterious host. Over dinner, a recorded message accuses each of them of harboring a guilty secret, and by the end of the night one guest is dead. Stranded by a storm, they begin to die one by one — following the verses of an old nursery rhyme displayed in each room. Only the dead are above suspicion.", wikipediaUrl: "https://en.wikipedia.org/wiki/And_Then_There_Were_None" },
  { title: "The Girl on the Train", author: "Paula Hawkins", description: "A woman who watches a couple from her commuter train becomes entangled in a missing persons investigation.", price: 12.99, genre: "Mystery", rating: 3.9, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9781594634024-L.jpg", fullDescription: "Rachel takes the same commuter train every morning and evening. Every day she rattles along the track, flashes past a stretch of cozy suburban houses, and stops at the signal that allows her to daily watch the same couple having breakfast on their deck. She's even started to feel like she knows them. Their life — as she sees it — is perfect. Then she sees something shocking, and everything changes.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Girl_on_the_Train_(novel)" },
  { title: "In the Woods", author: "Tana French", description: "A detective investigates a murder in the same woods where his childhood friends vanished twenty years ago.", price: 13.49, genre: "Mystery", rating: 4.1, inStock: false, coverImage: "https://covers.openlibrary.org/b/isbn/9780143113492-L.jpg", fullDescription: "When he was twelve, Adam Robert Ryan went playing in the woods with his two best friends. He was found gripping a tree trunk with his fingernails, his shoes filled with blood. Of his friends, no trace was ever found. Twenty years later, Rob is a detective on the Dublin Murder Squad and his teammate Cassie Maddox is his closest friend. When a twelve-year-old girl is found murdered in the same woods, Rob must revisit the horrors of childhood.", wikipediaUrl: "https://en.wikipedia.org/wiki/In_the_Woods" },
  // Horror (5)
  { title: "The Shining", author: "Stephen King", description: "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.", price: 14.99, genre: "Horror", rating: 4.5, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780307743657-L.jpg", fullDescription: "Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to spend reconnecting with his family and working on his writing. But as the harsh winter weather sets in, the idyllic location feels ever more remote — and more sinister. Danny, Jack's young son, possesses an extrasensory gift known as 'the shining' that allows him to see the hotel's terrifying past.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Shining_(novel)" },
  { title: "Dracula", author: "Bram Stoker", description: "The classic tale of Count Dracula's attempt to move from Transylvania to England to spread the undead curse.", price: 9.99, genre: "Horror", rating: 4.3, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780141439846-L.jpg", fullDescription: "When Jonathan Harker visits Transylvania to help Count Dracula purchase a London house, he makes horrifying discoveries about his client. Soon afterward, disturbing incidents unfold in England: a ship runs aground with a dead captain, a young woman's mysterious illness, and strange puncture marks on her neck. The legendary Abraham Van Helsing is summoned to confront the ancient evil of the undead Count.", wikipediaUrl: "https://en.wikipedia.org/wiki/Dracula" },
  { title: "Frankenstein", author: "Mary Shelley", description: "A young scientist creates a sapient creature in an unorthodox experiment, only to face tragic consequences.", price: 8.99, genre: "Horror", rating: 4.2, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780141439471-L.jpg", fullDescription: "Obsessed with the secret of creation, Swiss scientist Victor Frankenstein cobbles together a body from stolen parts and brings it to life. But the creature is rejected by Frankenstein and society alike, condemned to isolation and loneliness. Desperate for companionship, the creature turns to violence. A profound exploration of what it means to be human, Frankenstein remains the most enduring horror story ever written.", wikipediaUrl: "https://en.wikipedia.org/wiki/Frankenstein" },
  { title: "It", author: "Stephen King", description: "A group of children confront a shapeshifting evil that has plagued their small town for centuries.", price: 16.99, genre: "Horror", rating: 4.4, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9781501142970-L.jpg", fullDescription: "Welcome to Derry, Maine. It's a small city, a place as hauntingly familiar as your own hometown. Only in Derry the weights of shadows seem to weigh a little more. They know all about the town's dark past. In 1958, as children, they formed 'The Losers Club' to combat a shapeshifting evil that preys on children. Twenty-seven years later, the horror returns, and the group is called back to confront It once more.", wikipediaUrl: "https://en.wikipedia.org/wiki/It_(novel)" },
  { title: "The Haunting of Hill House", author: "Shirley Jackson", description: "Four seekers arrive at a notoriously unfriendly house to study its supernatural phenomena.", price: 11.99, genre: "Horror", rating: 4.2, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780143039983-L.jpg", fullDescription: "First published in 1959, Shirley Jackson's The Haunting of Hill House has been hailed as a perfect work of unnerving terror. Dr. Montague, an occult scholar, organizes an expedition to Hill House, a notoriously scary old mansion. He selects a small group of assistants who he feels are most likely to be sensitive to any paranormal activity. The house is gathering its powers — and soon it will choose one of them to make its own.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Haunting_of_Hill_House" },
  // Non-Fiction (5)
  { title: "Sapiens", author: "Yuval Noah Harari", description: "A brief history of humankind, exploring how Homo sapiens came to dominate the planet.", price: 16.99, genre: "Non-Fiction", rating: 4.5, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg", fullDescription: "One hundred thousand years ago, at least six different species of humans inhabited Earth. Yet today there is only one — Homo sapiens. What happened to the others? And what may happen to us? In Sapiens, Dr. Yuval Noah Harari spans the whole of human history, from the very first humans to walk the earth to the radical breakthroughs of the Cognitive, Agricultural, and Scientific Revolutions.", wikipediaUrl: "https://en.wikipedia.org/wiki/Sapiens:_A_Brief_History_of_Humankind" },
  { title: "Educated", author: "Tara Westover", description: "A memoir of a woman who grows up in a survivalist family and eventually earns a PhD from Cambridge.", price: 14.99, genre: "Non-Fiction", rating: 4.6, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg", fullDescription: "Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom. Her family was so isolated from mainstream society that there was no one to ensure the children received an education. When another brother got himself into college, Tara decided to try a new kind of life. Her quest for knowledge transformed her, taking her to Harvard and Cambridge.", wikipediaUrl: "https://en.wikipedia.org/wiki/Educated_(book)" },
  { title: "Becoming", author: "Michelle Obama", description: "The former First Lady chronicles her journey from Chicago's South Side to the White House.", price: 15.99, genre: "Non-Fiction", rating: 4.5, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg", fullDescription: "In a life filled with meaning and accomplishment, Michelle Obama has emerged as one of the most iconic and compelling women of our era. In her memoir, she chronicles the experiences that have shaped her, from growing up on the South Side of Chicago to her years as an executive balancing motherhood and work, to her time spent as First Lady of the United States.", wikipediaUrl: "https://en.wikipedia.org/wiki/Becoming_(book)" },
  { title: "The Immortal Life of Henrietta Lacks", author: "Rebecca Skloot", description: "The story of the woman whose cancer cells were taken without her knowledge and became vital to medical research.", price: 13.49, genre: "Non-Fiction", rating: 4.4, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9781400052189-L.jpg", fullDescription: "Her name was Henrietta Lacks, but scientists know her as HeLa. She was a poor Southern tobacco farmer, yet her cells — taken without her knowledge — became one of the most important tools in medicine. The first 'immortal' human cells grown in culture, they are still alive today. This book tells the extraordinary story of the Lacks family and of how her supposedly immortal cells became both a cornerstone of modern medicine and a source of deep ethical questions.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Immortal_Life_of_Henrietta_Lacks" },
  { title: "Thinking, Fast and Slow", author: "Daniel Kahneman", description: "A Nobel laureate reveals the two systems that drive the way we think and make decisions.", price: 15.49, genre: "Non-Fiction", rating: 4.3, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg", fullDescription: "In this international bestseller, Daniel Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think. System 1 is fast, intuitive, and emotional; System 2 is slower, more deliberative, and more logical. The impact of overconfidence on corporate strategies, the difficulties of predicting what will make us happy, and the profound effect of cognitive biases on everything we do are explored.", wikipediaUrl: "https://en.wikipedia.org/wiki/Thinking,_Fast_and_Slow" },
  // Adventure (5)
  { title: "Treasure Island", author: "Robert Louis Stevenson", description: "A young boy finds a treasure map and sets sail on a perilous journey with a crew that includes Long John Silver.", price: 9.99, genre: "Adventure", rating: 4.3, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780141321004-L.jpg", fullDescription: "When young Jim Hawkins discovers a treasure map among the possessions of a mysterious lodger, he sets off on a perilous voyage to a distant island. Along the way he meets the charming and treacherous Long John Silver, a one-legged pirate whose cunning is matched only by his ruthlessness. This timeless adventure tale has been captivating readers with its vivid characters and thrilling plot since 1883.", wikipediaUrl: "https://en.wikipedia.org/wiki/Treasure_Island" },
  { title: "The Adventures of Sherlock Holmes", author: "Arthur Conan Doyle", description: "A collection of twelve detective stories featuring the brilliant and eccentric Sherlock Holmes.", price: 10.99, genre: "Adventure", rating: 4.5, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780140437713-L.jpg", fullDescription: "From the Baker Street rooms he shares with Dr. Watson, Sherlock Holmes grapples with twelve classic cases. From a King of Bohemia requesting Holmes's help to recover a photograph, to the mystery of the speckled band and the case of a missing racehorse — each tale showcases Holmes's extraordinary powers of observation and deduction as he solves seemingly impossible crimes.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Adventures_of_Sherlock_Holmes" },
  { title: "The Count of Monte Cristo", author: "Alexandre Dumas", description: "A young sailor is falsely imprisoned and escapes to exact elaborate revenge on those who betrayed him.", price: 12.99, genre: "Adventure", rating: 4.7, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780140449266-L.jpg", fullDescription: "Thrown in prison for a crime he has not committed, Edmond Dantès is confined to the grim fortress of If. There he learns of a great hoard of treasure hidden on the Isle of Monte Cristo. Eventually escaping, Dantès acquires the treasure and assumes the identity of the Count of Monte Cristo. He returns to Marseille, rich and powerful, to exact his elaborate and all-consuming revenge on the three men responsible for his years of torment.", wikipediaUrl: "https://en.wikipedia.org/wiki/The_Count_of_Monte_Cristo" },
  { title: "Life of Pi", author: "Yann Martel", description: "A boy survives 227 days on a lifeboat in the Pacific Ocean with a Bengal tiger.", price: 13.49, genre: "Adventure", rating: 4.3, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780156027328-L.jpg", fullDescription: "After the sinking of a cargo ship, the sole human survivor is a sixteen-year-old boy named Pi Patel. He is alone on a lifeboat in the Pacific Ocean, with a 450-pound Royal Bengal tiger named Richard Parker. Pi must use every ounce of his will and ingenuity to survive the 227-day ordeal. A story that will make you believe in the power of imagination and the need for story itself.", wikipediaUrl: "https://en.wikipedia.org/wiki/Life_of_Pi" },
  { title: "Into the Wild", author: "Jon Krakauer", description: "The true story of Christopher McCandless who gave up everything to live in the Alaskan wilderness.", price: 12.49, genre: "Adventure", rating: 4.2, inStock: true, coverImage: "https://covers.openlibrary.org/b/isbn/9780385486804-L.jpg", fullDescription: "In April 1992, a young man from a well-to-do family hitchhiked to Alaska and walked alone into the wilderness north of Mt. McKinley. His name was Christopher Johnson McCandless. He had given away his savings, abandoned his car and most of his possessions, and burned the cash in his wallet. Four months later, his body was found by a moose hunter. Jon Krakauer explores the obsession that led McCandless into the wild.", wikipediaUrl: "https://en.wikipedia.org/wiki/Into_the_Wild_(book)" },
];

const users = [
  { username: "admin", password: "Admin123!", fullName: "Aleksandra Milosevic", phone: "0612345678", email: "admin@gmail.com" },
  { username: "isidora", password: "Pass123!", fullName: "Isidora Obradovic", phone: "0612345678", email: "isidora@gmail.com" },
  { username: "jelica", password: "Pass123!", fullName: "Jelica Cincovic", phone: "0612345679", email: "jelica@gmail.com" },
  { username: "drazen", password: "Pass123!", fullName: "Drazen Draskovic", phone: "0612345680", email: "drazen@gmail.com" },
  { username: "milica", password: "Pass123!", fullName: "Milica Milosevic", phone: "0612345681", email: "milica@gmail.com" },
  { username: "vojin", password: "Pass123!", fullName: "Vojin Vojnovic", phone: "0612345682", email: "vojin@gmail.com" },
];

async function main() {
  console.log("Seeding books...");

  for (const book of books) {
    await prisma.book.upsert({
      where: { title: book.title },
      update: { coverImage: book.coverImage, fullDescription: book.fullDescription, wikipediaUrl: book.wikipediaUrl },
      create: book,
    });
  }

  console.log(`Seeded ${books.length} books.`);

  console.log("Seeding users...");

  for (const user of users) {
    await prisma.user.upsert({
      where: { username: user.username },
      update: {},
      create: user,
    });
  }

  console.log(`Seeded ${users.length} users.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
